### ISSUE TITLE
[Version 2] Bug Tracker

### ISSUE THREAD

**Issue by CriticalFlaw** [CriticalFlaw/FlawBOT#6]
### Version 2.5
- [x] `steam user` command is not returning results if a user is not found. (75186ddd03761fe7c9cd55f0bddccafe45df51c2)
- [x] `tf2 schema` cannot parse some item names ie. Max's Head, Natasha. (75186ddd03761fe7c9cd55f0bddccafe45df51c2)
- [x] `tf2 map` requires the exact map name to be provided (75186ddd03761fe7c9cd55f0bddccafe45df51c2)
- [x] `color` and `pokemon` commands are not returning results. (65364daf94bfccb598093a6d7769b536e17fc1cd)

### Version 2.4
- [X] Add commands for creating and removing emojis. (bd673fd4fa3a615b188be14f7c9989c1b358f4c7)
- [X] `.book` is not returning any results. (5072cf9450da6ad9f5da63a24d1841a808c39e8e)
- [X] `.reddit` command does not consistently return results. (eb0e5ee310ced60ee857651d0a6736c3feb84008)

### Version 2.3
- [x] Update the Team Fortress module.
   - [x] Add pagination to the `news` command. (fab87ce9919adc99bc0db3916e8ee5f549837ee9)
   - [x] The `servers` command is not returning any results. (fab87ce9919adc99bc0db3916e8ee5f549837ee9)
- [x] Update the Reddit module.
   - [x] Add commands for top, hot and new subreddit posts.  (d16d84d69822c8ca5b0a919a22690cadf9edfd1f)
- [x] Add a command for retrieving IP address location. (d16d84d69822c8ca5b0a919a22690cadf9edfd1f)
- [x] Add a command for retrieving the news (Google News). (d16d84d69822c8ca5b0a919a22690cadf9edfd1f)
- [x] Add a command for retrieving book information (GoodReads). (52b455ca91ec22618cb74333ff5095436015c696)
- [X] The Reddit commands are not returning any results.

### Version 2.2
- [x] Update the Team Fortress module
   - [x] Fix the `item` command not retrieving items from the schema (ca543a905825efe05fa4f372e01c96d5aaef56ed)
   - [x] Move the `connect` command to the Steam module (ee45d91bfb53337a82ac6e07146e7051790d0d76)
- [x] Update the Smash Brothers module
   - [x] Add output fields for character attributes
- [x] Update the Speedrun module
   - [x] Search for common games is inconsistent (ca543a905825efe05fa4f372e01c96d5aaef56ed)
   - [X] Add more details and speedrun information to existing command (822313d887b9a1f900965c499326bb13583a5b7d)
- [X] Add exception handling for ChecksFailed exceptions (e79aa1c4b44517c88928980a45f72d5e38695495)
- [X] Fix any user being able to respond to the `bot leave` command (e79aa1c4b44517c88928980a45f72d5e38695495)
